# Generated by Django 3.2.8 on 2025-03-03 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wxcloudrun', '0011_add_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='等级名称')),
                ('description', models.TextField(blank=True, verbose_name='等级描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '成就等级',
                'verbose_name_plural': '成就等级',
                'db_table': 'achievement_level',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='考核名称')),
                ('description', models.TextField(blank=True, verbose_name='考核描述')),
                ('assessment_date', models.DateField(verbose_name='考核日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '考核',
                'verbose_name_plural': '考核',
                'db_table': 'assessment',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='考核项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='最高分值')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wxcloudrun.assessment', verbose_name='所属考核')),
            ],
            options={
                'verbose_name': '考核项目',
                'verbose_name_plural': '考核项目',
                'db_table': 'assessment_item',
                'ordering': ['assessment', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='队伍名称')),
                ('status', models.CharField(choices=[('active', '活跃中'), ('disbanded', '已解散')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coaches', models.ManyToManyField(related_name='coached_teams', to='wxcloudrun.Coach', verbose_name='教练')),
                ('head_coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='headed_teams', to='wxcloudrun.coach', verbose_name='主教练')),
                ('players', models.ManyToManyField(related_name='teams', to='wxcloudrun.Player', verbose_name='队员')),
            ],
            options={
                'verbose_name': '队伍',
                'verbose_name_plural': '队伍',
                'db_table': 'team',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_name', models.CharField(max_length=200, verbose_name='比赛名称')),
                ('competition_date', models.DateField(verbose_name='比赛日期')),
                ('result', models.CharField(max_length=100, verbose_name='成绩')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='wxcloudrun.team', verbose_name='队伍')),
            ],
            options={
                'verbose_name': '队伍成绩',
                'verbose_name_plural': '队伍成绩',
                'db_table': 'team_result',
                'ordering': ['-competition_date'],
            },
        ),
        migrations.CreateModel(
            name='TeamAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='成就名称')),
                ('description', models.TextField(blank=True, verbose_name='成就描述')),
                ('competition_name', models.CharField(blank=True, max_length=200, verbose_name='比赛名称')),
                ('awarded_date', models.DateField(verbose_name='获得日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='颁发人')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='wxcloudrun.team', verbose_name='队伍')),
            ],
            options={
                'verbose_name': '队伍成就',
                'verbose_name_plural': '队伍成就',
                'db_table': 'team_achievement',
                'ordering': ['-awarded_date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('description', models.TextField(verbose_name='任务描述')),
                ('period', models.CharField(choices=[('daily', '每日'), ('weekly', '每周'), ('monthly', '每月'), ('once', '一次性')], default='once', max_length=20, verbose_name='任务周期')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('teams', models.ManyToManyField(related_name='tasks', to='wxcloudrun.Team', verbose_name='分配队伍')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='成就名称')),
                ('description', models.TextField(blank=True, verbose_name='成就描述')),
                ('achievement_type', models.CharField(choices=[('manual', '手动发放'), ('task', '任务完成'), ('assessment', '考核成绩')], default='manual', max_length=20, verbose_name='获取方式')),
                ('task_count', models.IntegerField(default=0, verbose_name='任务完成次数要求')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wxcloudrun.achievementlevel', verbose_name='成就等级')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wxcloudrun.task', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '个人成就',
                'verbose_name_plural': '个人成就',
                'db_table': 'personal_achievement',
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='teams',
            field=models.ManyToManyField(related_name='assessments', to='wxcloudrun.Team', verbose_name='参与队伍'),
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(verbose_name='完成日期')),
                ('proof', models.ImageField(blank=True, null=True, upload_to='task_proofs/', verbose_name='完成证明')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('verified', models.BooleanField(default=False, verbose_name='是否已验证')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to='wxcloudrun.player', verbose_name='队员')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='wxcloudrun.task', verbose_name='任务')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tasks', to=settings.AUTH_USER_MODEL, verbose_name='验证人')),
            ],
            options={
                'verbose_name': '任务完成记录',
                'verbose_name_plural': '任务完成记录',
                'db_table': 'task_completion',
                'ordering': ['-completion_date'],
                'unique_together': {('task', 'player', 'completion_date')},
            },
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_date', models.DateField(verbose_name='获得日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxcloudrun.personalachievement', verbose_name='成就')),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='颁发人')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='wxcloudrun.player', verbose_name='队员')),
            ],
            options={
                'verbose_name': '队员成就记录',
                'verbose_name_plural': '队员成就记录',
                'db_table': 'player_achievement',
                'ordering': ['-awarded_date'],
                'unique_together': {('player', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='得分')),
                ('notes', models.TextField(blank=True, verbose_name='评分备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='wxcloudrun.assessment', verbose_name='考核')),
                ('assessment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='wxcloudrun.assessmentitem', verbose_name='考核项目')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_scores', to='wxcloudrun.player', verbose_name='队员')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
            ],
            options={
                'verbose_name': '考核成绩',
                'verbose_name_plural': '考核成绩',
                'db_table': 'assessment_score',
                'ordering': ['assessment', 'player', 'assessment_item'],
                'unique_together': {('assessment', 'assessment_item', 'player')},
            },
        ),
    ]
