# Generated by Django 3.2.8 on 2025-03-05 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0013_create_coach_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类别名称')),
                ('description', models.TextField(blank=True, verbose_name='类别描述')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='achievement_icons/', verbose_name='类别图标')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '成就类别',
                'verbose_name_plural': '成就类别',
                'db_table': 'achievement_category',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='personalachievement',
            name='level',
        ),
        migrations.DeleteModel(
            name='AchievementLevel',
        ),
        migrations.AddField(
            model_name='personalachievement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wxcloudrun.achievementcategory', verbose_name='成就类别'),
        ),
    ]
