# Generated by Django 3.2.8 on 2025-03-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0014_auto_20250305_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='头像URL'),
        ),
    ]
