# Generated by Django 3.2.8 on 2025-03-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0015_player_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='jersey_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='背号'),
        ),
    ]
