# Generated by Django 3.2.8 on 2025-03-08 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wxcloudrun', '0016_player_jersey_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类型名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='类型描述')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='图标')),
                ('color', models.CharField(default='#1890ff', max_length=20, verbose_name='颜色')),
            ],
            options={
                'verbose_name': '任务类型',
                'verbose_name_plural': '任务类型',
            },
        ),
        migrations.RemoveField(
            model_name='personalachievement',
            name='category',
        ),
        migrations.RemoveField(
            model_name='personalachievement',
            name='task',
        ),
        migrations.AlterUniqueTogether(
            name='playerachievement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='playerachievement',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='playerachievement',
            name='awarded_by',
        ),
        migrations.RemoveField(
            model_name='playerachievement',
            name='player',
        ),
        migrations.RemoveField(
            model_name='teamachievement',
            name='awarded_by',
        ),
        migrations.RemoveField(
            model_name='teamachievement',
            name='team',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='teams',
        ),
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.IntegerField(default=1, verbose_name='积分值'),
        ),
        migrations.AddField(
            model_name='task',
            name='require_proof',
            field=models.BooleanField(default=False, verbose_name='是否需要证明'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('active', '活跃中'), ('completed', '已结束'), ('expired', '已过期'), ('draft', '草稿')], default='active', max_length=10, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='wxcloudrun.team', verbose_name='所属队伍'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='task',
            name='period',
            field=models.CharField(choices=[('once', '一次性'), ('daily', '每日'), ('weekly', '每周'), ('monthly', '每月')], default='once', max_length=20, verbose_name='频率'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='notes',
            field=models.TextField(verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxcloudrun.player', verbose_name='完成队员'),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='proof',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='证明'),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxcloudrun.task', verbose_name='关联任务'),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='验证人'),
        ),
        migrations.DeleteModel(
            name='AchievementCategory',
        ),
        migrations.DeleteModel(
            name='PersonalAchievement',
        ),
        migrations.DeleteModel(
            name='PlayerAchievement',
        ),
        migrations.DeleteModel(
            name='TeamAchievement',
        ),
    ]
