# Generated by Django 3.2.8 on 2025-03-08 14:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wxcloudrun', '0018_auto_20250308_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类别名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='类别描述')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='图标')),
                ('color', models.CharField(default='#1890ff', max_length=20, verbose_name='颜色')),
                ('cover_image', models.URLField(blank=True, null=True, verbose_name='封面图片')),
                ('order', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '成就类别',
                'verbose_name_plural': '成就类别',
                'db_table': 'achievement_category',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PersonalAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='成就名称')),
                ('description', models.TextField(blank=True, verbose_name='成就描述')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='积分')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='图标')),
                ('badge_image_locked', models.URLField(blank=True, null=True, verbose_name='未解锁徽章图片')),
                ('badge_image', models.URLField(blank=True, null=True, verbose_name='徽章图片')),
                ('badge_animation', models.URLField(blank=True, null=True, verbose_name='徽章解锁动画')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难'), ('expert', '专家'), ('master', '大师')], default='medium', max_length=10, verbose_name='难度')),
                ('rarity', models.CharField(choices=[('common', '普通'), ('uncommon', '不常见'), ('rare', '稀有'), ('epic', '史诗'), ('legendary', '传奇')], default='common', max_length=10, verbose_name='稀有度')),
                ('hidden', models.BooleanField(default=False, verbose_name='是否隐藏成就')),
                ('featured', models.BooleanField(default=False, verbose_name='是否精选成就')),
                ('criteria_type', models.CharField(choices=[('manual', '手动颁发'), ('auto_task', '自动(任务)'), ('auto_assessment', '自动(考核)')], default='manual', max_length=20, verbose_name='颁发方式')),
                ('criteria_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='条件值')),
                ('criteria_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='条件描述')),
                ('unlock_message', models.TextField(blank=True, null=True, verbose_name='解锁提示信息')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_achievements', to='wxcloudrun.achievementcategory', verbose_name='所属类别')),
            ],
            options={
                'verbose_name': '个人成就',
                'verbose_name_plural': '个人成就',
                'db_table': 'personal_achievement',
                'ordering': ['category', 'difficulty', '-rarity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='成就名称')),
                ('description', models.TextField(blank=True, verbose_name='成就描述')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='积分')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='图标')),
                ('badge_image', models.URLField(blank=True, null=True, verbose_name='徽章图片')),
                ('awarded_date', models.DateField(default=datetime.date.today, verbose_name='获得日期')),
                ('notes', models.TextField(blank=True, verbose_name='颁发备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='颁发人')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_achievements', to='wxcloudrun.achievementcategory', verbose_name='所属类别')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='wxcloudrun.team', verbose_name='队伍')),
            ],
            options={
                'verbose_name': '队伍成就',
                'verbose_name_plural': '队伍成就',
                'db_table': 'team_achievement',
                'ordering': ['-awarded_date'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_date', models.DateField(default=datetime.date.today, verbose_name='获得日期')),
                ('notes', models.TextField(blank=True, verbose_name='颁发备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('progress', models.IntegerField(default=100, verbose_name='完成进度')),
                ('shared', models.BooleanField(default=False, verbose_name='是否已分享')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_records', to='wxcloudrun.personalachievement', verbose_name='成就')),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='颁发人')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='wxcloudrun.player', verbose_name='队员')),
            ],
            options={
                'verbose_name': '队员成就记录',
                'verbose_name_plural': '队员成就记录',
                'db_table': 'player_achievement',
                'ordering': ['-awarded_date'],
                'unique_together': {('player', 'achievement')},
            },
        ),
    ]
