# Generated by Django 3.2.8 on 2025-03-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0020_auto_20250308_1450'),
    ]

    operations = [
    ]
